# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

as_SNPv <- function(x, q) {
    .Call('_cshap_as_SNPv', PACKAGE = 'cshap', x, q)
}

as_LSNPv <- function(x, q) {
    .Call('_cshap_as_LSNPv', PACKAGE = 'cshap', x, q)
}

haplo <- function(q) {
    .Call('_cshap_haplo', PACKAGE = 'cshap', q)
}

haplo2 <- function(q, htn) {
    .Call('_cshap_haplo2', PACKAGE = 'cshap', q, htn)
}

create_psi <- function(q) {
    .Call('_cshap_create_psi', PACKAGE = 'cshap', q)
}

l2norm <- function(x) {
    .Call('_cshap_l2norm', PACKAGE = 'cshap', x)
}

l2normM <- function(A) {
    .Call('_cshap_l2normM', PACKAGE = 'cshap', A)
}

create_RM <- function(q) {
    .Call('_cshap_create_RM', PACKAGE = 'cshap', q)
}

haplo2RM <- function(H) {
    .Call('_cshap_haplo2RM', PACKAGE = 'cshap', H)
}

countint <- function(ux, x) {
    .Call('_cshap_countint', PACKAGE = 'cshap', ux, x)
}

countint_detail <- function(ux, x) {
    .Call('_cshap_countint_detail', PACKAGE = 'cshap', ux, x)
}

match_row <- function(x, A) {
    .Call('_cshap_match_row', PACKAGE = 'cshap', x, A)
}

count_row <- function(x, A) {
    .Call('_cshap_count_row', PACKAGE = 'cshap', x, A)
}

count_row_mat <- function(uA, A) {
    .Call('_cshap_count_row_mat', PACKAGE = 'cshap', uA, A)
}

which_row <- function(x, A) {
    .Call('_cshap_which_row', PACKAGE = 'cshap', x, A)
}

count_row_mat_detail <- function(uA, A) {
    .Call('_cshap_count_row_mat_detail', PACKAGE = 'cshap', uA, A)
}

match_col <- function(x, A) {
    .Call('_cshap_match_col', PACKAGE = 'cshap', x, A)
}

count_col <- function(x, A) {
    .Call('_cshap_count_col', PACKAGE = 'cshap', x, A)
}

count_col_mat <- function(uA, A) {
    .Call('_cshap_count_col_mat', PACKAGE = 'cshap', uA, A)
}

which_col <- function(x, A) {
    .Call('_cshap_which_col', PACKAGE = 'cshap', x, A)
}

count_col_mat_detail <- function(uA, A) {
    .Call('_cshap_count_col_mat_detail', PACKAGE = 'cshap', uA, A)
}

ligation_vec <- function(a, b) {
    .Call('_cshap_ligation_vec', PACKAGE = 'cshap', a, b)
}

rep1_mat <- function(A, n) {
    .Call('_cshap_rep1_mat', PACKAGE = 'cshap', A, n)
}

rep1_mat_fast <- function(A, n) {
    .Call('_cshap_rep1_mat_fast', PACKAGE = 'cshap', A, n)
}

